#!/system/bin/sh
if [[ ! -z $1 ]];then
	echo $1 > /sys/devices/virtual/misc/boeffla_sound/fll_tuning;
fi
echo `cat /sys/devices/virtual/misc/boeffla_sound/fll_tuning |  sed -n -e '/FLL tuning/ s/.*\: *//p'`;
