#!/system/bin/sh
if [[ ! -z $1 ]];then
	echo $1 > /sys/devices/virtual/misc/boeffla_sound/dac_direct;
fi
echo `cat /sys/devices/virtual/misc/boeffla_sound/dac_direct |  sed -n -e '/DAC direct/ s/.*\: *//p'`;
