#!/system/bin/sh
if [[ ! -z $1 ]];then
	echo $1 > /sys/devices/virtual/misc/boeffla_sound/dac_oversampling;
fi
echo `cat /sys/devices/virtual/misc/boeffla_sound/dac_oversampling |  sed -n -e '/DAC oversampling/ s/.*\: *//p'`;
