#!/system/bin/sh
if [[ ! -z $1 ]];then
	echo $1 > /sys/devices/virtual/misc/boeffla_sound/mono_downmix;
fi
echo `cat /sys/devices/virtual/misc/boeffla_sound/mono_downmix |  sed -n -e '/Mono downmix/ s/.*\: *//p'`;
