#!/system/bin/sh
EQ_NODE="/sys/devices/virtual/misc/boeffla_sound/eq_gains"
EQ_RAW=`cat $EQ_NODE |  sed -n -e '/EQ gains/ s/.*\: *//p'`;
arreq=(`echo ${EQ_RAW}`);
if [[ ! -z $1 ]];then
	if [[ ! -z $2 ]]; then
		arreq[$1]=$2;
		echo "${arreq[0]} ${arreq[1]} ${arreq[2]} ${arreq[3]} ${arreq[4]}" > $EQ_NODE;
	fi
	echo ${arreq[$1]};
fi
