#!/system/bin/sh
FREQRAW=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq`;
FREQ=`expr $FREQRAW / 1000`;
CORE0="$FREQ mhz";
ONLINE=`cat /sys/devices/system/cpu/cpu1/online`
CORE1="offline";
case $ONLINE in
			1)
				CORE1=$CORE0;;
esac;
ONLINE=`cat /sys/devices/system/cpu/cpu2/online`
CORE2="offline";
case $ONLINE in
			1)
				CORE2=$CORE0;;
esac;
ONLINE=`cat /sys/devices/system/cpu/cpu3/online`
CORE3="offline";
case $ONLINE in
			1)
				CORE3=$CORE0;;
esac;

echo "Core 0 : $CORE0@nCore 1 : $CORE1@nCore 2 : $CORE2@nCore 3 : $CORE3"
