#!/system/bin/sh
CURRGOV=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`;
CURRMIN=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`;
CURRMAX=`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`;
if [[ ! -z $1 ]];then
    if [[ ! -z $2 ]]; then
        case $1 in
			gov)
				echo $CURRMIN > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq;
				echo $CURRMAX > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
				echo $2 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;;
			min)
				echo $2 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq;
				echo $CURRMAX > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
				echo $CURRGOV > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;;
			max)
				echo $CURRMIN > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq;
				echo $2 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq;
				echo $CURRGOV > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor;;
		esac;
    fi

    case $1 in
			gov)
				echo `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor`;;
			min)
				echo `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`;;
			max)
				echo `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq`;;
		esac;
fi
